robot_control: add missing target_include_directories()
This includes the headers as describe in the Ament documentation[1].

Fixes (on Jazzy):

	/home/gportay/src/abmi-software/Robot5A-Simulation/src/robot_control/src/aruco_detector_double.cpp:4:10: fatal error: ament_index_cpp/get_package_share_directory.hpp: No such file or directory
	    4 | #include <ament_index_cpp/get_package_share_directory.hpp>  // Include ament_index_cpp
	      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
	compilation terminated.

[1]: https://docs.ros.org/en/foxy/How-To-Guides/Ament-CMake-Documentation.html#adding-files-and-headers