Bump to ROS2 Jazzy
This bumps the project to ROS2 Jazzy[1], based on Ubuntu Noble 24.04
LTS[2].

Fixes:

	In file included from /home/gportay/src/abmi-software/Robot5A-Simulation/src/robot_control/src/moveit_control_simple.cpp:5:
	/opt/ros/jazzy/include/moveit_ros_planning_interface/moveit/move_group_interface/move_group_interface.h:51:77: note: ‘#pragma message: .h header is obsolete. Please use the .hpp header instead.’
	   51 | #pragma message(".h header is obsolete. Please use the .hpp header instead.")
	      |                                                                             ^

And fixes:

	/home/gportay/src/abmi-software/Robot5A-Simulation/src/robot_control/src/aruco_detector_single.cpp:5:10: fatal error: cv_bridge/cv_bridge.h: No such file or directory
	    5 | #include <cv_bridge/cv_bridge.h>
	      |          ^~~~~~~~~~~~~~~~~~~~~~~
	compilation terminated.

[1]: https://docs.ros.org/en/jazzy/index.html
[2]: https://ubuntu.com/blog/tag/ubuntu-24-04-lts
[3]: https://gazebosim.org/docs/latest/migrating_gazebo_classic_ros2_packages/
[4]: https://gazebosim.org/api/sim/8/migrationsdf.html